export const familyMemberCardStyles = {
  card: "border-primary/10 bg-card/85",
  header: "space-y-2",
  titleRow: "flex flex-wrap items-center gap-2",
  content: "space-y-5",
  summaryGrid: "grid gap-3 lg:grid-cols-[1.35fr_0.9fr]",
  debitPanel: "rounded-xl border border-border/80 bg-background/55 p-4",
  panelHeader: "flex items-center justify-between gap-3",
  panelTitle: "text-sm font-semibold text-foreground",
  panelHint: "text-xs text-muted-foreground",
  availableBalance: "mt-1 text-xl font-semibold text-foreground",
  debitStatsGrid: "mt-4 grid gap-3 sm:grid-cols-3",
  stat: "space-y-1",
  statLabel: "text-xs text-muted-foreground",
  incomeValue: "text-lg font-semibold text-income",
  expenseValue: "text-lg font-semibold text-destructive",
  resultValue: "text-lg font-semibold text-foreground",
  creditPanel: "rounded-xl border border-primary/15 bg-primary/5 p-4",
  creditStat: "mt-4 space-y-1",
  creditValue: "text-xl font-semibold text-foreground",
  creditHint: "mt-4 text-xs leading-relaxed text-muted-foreground",
  latestList: "space-y-2",
  latestItem:
    "flex flex-wrap items-center justify-between gap-2 rounded-xl border border-border bg-background/70 px-3 py-2 text-sm",
  latestDescription: "font-medium text-foreground",
  latestMeta: "text-xs text-muted-foreground",
  latestAmount: "font-semibold text-foreground",
  emptyState: "bg-background/60"
};
